language: cpp

compiler:
  - clang
  - gcc

install:
  - mkdir build; cd build
  - cmake ..
  - make
  - cd ..

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.8
      - g++-4.8
      - zlib1g-dev
      - libbz2-dev
      - libboost-dev

script:
  - cd build
  - ctest -V
